name: yatta
description: A multipurpose YouTube frontend for hackers

publish_to: "none"

version: 0.1.0

environment:
    sdk: ">=2.18.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    fluent_ui: ^4.0.0
    youtube_api: ^1.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    extra_pedantic: ^3.0.0

flutter:
    uses-material-design: true
